# 1 job qui build et test l'application Next
# Puis sÃ©parer le build et le test en 2 jobs distincts
# Test dÃ©pend de build
# Mettre en cache node_modules entre les 2

name: BuildAndTest
run-name: ${{ github.actor }} is running first exercise ğŸš€
on: [push]
jobs:
  Test-NextJS-App:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Executing "npm install"
        run: npm install
      - name: Build application
        run: |
          npm run build
      - name: Run Cypress tests
        run: npm run e2e:headless
        continue-on-error: true

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos/

      # - name: Download Cypress test videos
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: cypress-videos
      #     path: /home/runner/work/cours-devops/cours-devops/cypress/videos/
      - run: echo "ğŸ This job's status is ${{ job.status }}."
