# 1 job qui build et test l'application Next
# Puis s√©parer le build et le test en 2 jobs distincts
# Test d√©pend de build
# Mettre en cache node_modules entre les 2

name: BuildAndTest
run-name: ${{ github.actor }} is running first exercise üöÄ
on: [push]
jobs:
  Build-NextJS-App:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4x
      - name: npm install and build application
        run: |
          npm install
          npm run build
      - name: Cache "node_modules"
        id: cache-node
        uses: actions/cache@v4
        with:
          path: 
            node_modules
            ../.cache/Cypress
          key: ${{ runner.os }}-node_modules
      - run: echo "üçè This job's status is ${{ job.status }}."

  Test-NextJS-App:
    needs: Build-NextJS-App
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Restore cached "node_modules"
        id: cache-node_modules-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ../.cache/Cypress
          key: ${{ runner.os }}-node_modules
      - name: Run Cypress tests
        run: npm run e2e:headless
        continue-on-error: true
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos/